include support for firmware upgrades

diff --git a/tree/usr/sbin/elive-upgrader-root b/tree/usr/sbin/elive-upgrader-root
--- a/tree/usr/sbin/elive-upgrader-root
+++ b/tree/usr/sbin/elive-upgrader-root
@@ -91,7 +91,7 @@ apt_fixes(){
     if ((is_failed)) ; then
         local message_failed
         message_failed="$( printf "$( eval_gettext "Seems like you have a broken state of your packages. Please open a terminal and run the command '%s'. If you cannot solve the issue you can try to reinstall your Elive system, the installer features an upgrade mode." )" "apif" )"
-        zenity --error --text="$message_failed"
+        $guitool --error --text="$message_failed"
     fi
 }
 hooks_root(){
@@ -168,13 +168,86 @@ upgrade_system(){
     fi
 
     if ((is_upgraded)) ; then
-        if zenity --question --text="$( eval_gettext "Your Elive has been upgraded with improvements and fixes. Do you want to donate to this amazing project in order to keep it progressing?" )" ; then
+        if $guitool --question --text="$( eval_gettext "Your Elive has been upgraded with improvements and fixes. Do you want to donate to this amazing project in order to keep it progressing?" )" ; then
             web-launcher "http://www.elivecd.org/donate/?id=elive-upgrader-tool-fullupgrade"
         fi
     fi
 
     # remove flag
     rm -f "/tmp/.elive-upgrading" 1>/dev/null 2>&1 || true
+}
+
+upgrade_firmwares(){
+    # pre {{{
+
+    if el_check_dir_has_files "/sys/firmware/efi/" 1>/dev/null 2>&1 ; then
+        if el_check_dir_has_files "/sys/firmware/efi/efivars" 1>/dev/null 2>&1 ; then
+            is_efi_booted=1
+
+            if [[ -x "$( which efivar )" ]] ; then
+                if ! [[ "$( efivar -l 2>/dev/null | wc -l )" -ge 1 ]] ; then
+                    unset is_efi_booted
+                fi
+            fi
+        fi
+    fi
+
+    # - pre }}}
+
+    if ((is_efi_booted)) ; then
+        # refresh packages lists:
+        fwupdmgr refresh # 1>/dev/null  # requires 300 KB of internet
+        # show updates:
+        fwupdmgr get-updates # 1>/dev/null
+
+        if LC_ALL="$EL_LC_EN" fwupdmgr get-updates | grep -qs "^Update Name:" ; then
+
+            # notify
+            $guitool --info --text="$( eval_gettext "Firmware updates have been found for your hardware." )"
+
+            # display updates
+            while read -ru 3 line
+            do
+                [[ -z "$line" ]] && continue
+                case "$line" in
+                    "Update Version:"*)
+                        echo -e "\n\n${line}"
+                        continue
+                        ;;
+                        "Update Name:"*)
+                        echo "$line"
+                        continue
+                        ;;
+                    "Update Description"*)
+                        line="${line#Update Description:}"
+                        read -r line <<< "$line"
+
+                        echo -e "\n        ${line}"
+                        ;;
+                    "Update"*|"GUID:"*|"ID:"*)
+                        continue
+                        ;;
+                    *)
+                        echo "        $line"
+                        ;;
+                esac
+            done 3<<< "$( LC_ALL="$EL_LC_EN" fwupdmgr get-updates )" | $guitool --height=400 --text-info --cancel-label="Done" --title="$( eval_gettext "Firmware Updates available:" )"
+
+
+            # ask to install
+            if $guitool --question --text="$( eval_gettext "Do you want to install these firmware updates for your hardware?" )" ; then
+                fwupdmgr update
+            else
+                # we should remember the selection of "no"? the normal is that the user should always want to update firmware, but maybe not the first time and probably the second one, so do not remember this choice and instead, ask the question in every full upgrade request
+                true
+                #updates_list="$( fwupdmgr get-updates | grep "^Update Version:" | sort -u )"
+            fi
+
+        fi
+    else
+        el_info "Firmware upgrades requires UEFI, ignoring..."
+    fi
+
 }
 
 
@@ -225,7 +298,7 @@ update_upgrader_fast(){
         #apt_get dist-upgrade -y --force-yes
 
         #if ! apt_get -y -f install ; then
-            #zenity --error --text="$( eval_gettext "Seems like you have a broken state of your packages. Check our Elive Forums for a solution if you are unable to solve it yourself. Showing the result of the command:" ) apug"
+            #$guitool --error --text="$( eval_gettext "Seems like you have a broken state of your packages. Check our Elive Forums for a solution if you are unable to solve it yourself. Showing the result of the command:" ) apug"
             #el_error "Problem with apt-get -y -f install (reported): $(apt-get -y -f install 2>&1 )"
             #exit 1
         #fi
@@ -271,6 +344,9 @@ main(){
                 ;;
             --updates-available)
                 updates_available_show
+                ;;
+            --upgrade-firmwares)
+                upgrade_firmwares
                 ;;
             --fix)
                 apt_fixes
